name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Uninstall 31.0.0 Build tool
      run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager --uninstall 'build-tools;31.0.0'
    - name: Assemble with Gradle
      run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@v2
      with:
        name: appDebug
        path: app/build/outputs/apk/debug/app-debug.apk
